README.md
=> Add description in readme.md

common_core.c, common_core.h, request/request.h, request/ta_find_transactions.c, request/ta_find_transactions.h, response/response.h, response/ta_find_transactions.c, response/ta_find_transactions.h
Implement `ta_find_transaction_by_tag` core function and also request/response files.
Fix #4
=> Implement ta_find_transaction_by_tag core function

BUILD, WORKSPACE, common_core.c, request/ta_find_transactions.h, request/ta_send_transfer.c, request/ta_send_transfer.h, response/ta_generate_address.c, response/ta_generate_address.h, response/ta_get_tips.c, response/ta_get_tips.h, response/ta_send_transfer.c, response/ta_send_transfer.h, serializer/serializer.c, serializer/serializer.h, serializer/test/test_serializer.c, serializer/test/test_serializer.h
=> Fix build error

.bazelrc
Add follow config options in .bazelrc:
* Address Sanitizer
* Thread Sanitizer
* Undefined Behavior Sanitizer
=> Add bazel configurations

WORKSPACE, common_core.c, common_core.h, request/request.h, request/ta_get_transaction_msg.c, request/ta_get_transaction_msg.h, response/response.h, response/ta_get_transaction_msg.c, response/ta_get_transaction_msg.h
Close #5 
I've tested with node10, [source code](https://github.com/jkrvivian/entangled/blob/0a50526ecd61c4ff3d19b98be5c36b951fc6cc8f/cclient/test_api/cclient_test.c#L107)
=> Implement ta_get_transaction_msg core function

apis.h, common_core.h, config.h, request/ta_find_transactions.h, request/ta_get_tips.h, request/ta_get_transaction_msg.h, request/ta_send_transfer.h, response/ta_find_transactions.h, response/ta_generate_address.h, response/ta_get_tips.h, response/ta_get_transaction_msg.h, response/ta_send_transfer.h, serializer/serializer.h, serializer/test/test_serializer.h
We are going to use googletest and boost library which are in C++. C header files need extern c for them to include.
=> Add extern c to all header files

accelerator/server.cc
=> feat: Add HTTP OPTIONS to allow CROS request

WORKSPACE
This update fix filling obsolete_tag to tag while finalizing bundle in send_transfer.
=> fix: Update cclient to latest development

.gitmodules
Move pow submoodule to specific tag v0.1.0 so we don't need to worry
dependency if dcurl is updated.
CI must pass.
=> feat: update pow submodule to v0.1.0

accelerator/BUILD, accelerator/apis.c, accelerator/apis.h, accelerator/common_core.c, accelerator/common_core.h, accelerator/errors.h, serializer/BUILD, serializer/serializer.c, serializer/serializer.h, tests/iota_api_mock.cc, tests/iota_api_mock.hh, utils/BUILD, utils/backend_redis.c, utils/cache.h, utils/pow.c, utils/pow.h
=> feat: Implement status code

accelerator/common_core.c
Send_transfer would now cache transaction infos to cache. When
performing attach_to_tangle, raw transaction trytes would store as value
to cache, then find_transaction action will search transaction directly
through memory after broadcast_and_store.
Resolve #78
=> feat(core): cache send_transfer

accelerator/errors.h, serializer/serializer.c, utils/backend_redis.c
* Fix incorrect status code in `cache`
* Remove unused status code
* Add `SC_CCLIENT_NOT_FOUND` for empty result
* This will be use in #86
=> Modify status code

WORKSPACE, accelerator/BUILD, accelerator/common_core.h, tests/BUILD, tests/iota_api_mock.cc, tests/iota_api_mock.hh
cclient api header files have changed directories.
=> fix(entangled): Update cclient api headers

.bazelrc
Add bazel coverage configurations. Report generation is included in
buildkite CI and would be uploaded to artifact.
Resolve #87
=> feat(test): Add code coverage configs

accelerator/config.h, accelerator/errors.h, accelerator/server.cc
Add "tangle-accelerator" as server name and version to the header.
Versioning is also added to config header file. Future releases require
update this macro.
=> feat(server): Add Server name in header

accelerator/BUILD, accelerator/apis.c, accelerator/apis.h, accelerator/common_core.c, accelerator/common_core.h, accelerator/config.c, accelerator/config.h, accelerator/server.cc, tests/driver.c, tests/iota_api_mock.cc, tests/iota_api_mock.hh, tests/test_common.cc
Refactor configuration variables for future cli and file config feature.
This also enable logger helper to record initializations and destroys.
This PR also fix all functions and test cases related to this change.
Part of #114
=>  feat(config): Refactor configuration variables

tests/driver.c
=> feat(test): Implement time utility functions

README.md
Version badge will be added in release PR.
=> fix(README): Add CI and chat badges

Makefile
Update dcurl version to v0.2.0 and edit Makefile to force dcurl pin to
certain version in the release.
=> feat(dcurl): Update dcurl version

accelerator/apis.c, serializer/serializer.c, serializer/serializer.h
=> feat(serializer): Add receive_mam_message serialize

accelerator/apis.c, accelerator/apis.h, accelerator/common_core.c, accelerator/common_core.h, accelerator/config.c, accelerator/config.h, accelerator/errors.h, tests/driver.c, tests/test_define.h
Implement `api_mam_send_message()` and related test, function.
One function was implemented is `mam_send_bundle()` whose arg is bundle.
=> feat(mam): Implement api_mam_send_message()

request/ta_send_mam_req.h
Remove some needless inclusion in `send_mam_req.h`
=> fix(mam): Remove needless send_mam_req inclusion

tests/regression/runner.py
The functions in class Time_Consumption() calculate how long does
each API cost. Each API is called for 100 times, and then, calculate its
average time costs and time cost variance.
=> feat: Add MAM regression test time cost statistics

accelerator/errors.h
There are some error number in the wrong ordering.
associates #158
=> fix(error) Fix error code wrong ordering

BUILD, README.md, accelerator/config.h
There are some minor tweaks needed before another release:
* fix(bazel): Obey buildifier style
* fix(README): Update README badges
=> Preparation for pre-release v0.5.0

accelerator/server.cc
Evaluate whole status_t code instead part of it (actual error code).
=> fix(server): Evaluate whole status_t code in server.cc

tests/driver.c
Wrong testing message is printed during driver test
=> fix(driver): Fix wrong testing info

tests/regression/0_pull_build.sh, tests/regression/1_run_regression_test.sh, tests/regression/requirements.txt
This shell script must be run at root directory of the repo.
CI must be updated to run this test.
For the dependency problems, the `requirements.txt` is included in this PR.
=> feat(reg): Add shell script for running runner.py

accelerator/BUILD, accelerator/main.c
- Add signal handler for SIGINT and SIGTERM, using signal helper functions in entangled
- Add logger when error occurred, starting and destroying TA
Close #175
=> feat(server): Implement signal handler to terminate TA

accelerator/errors.h, serializer/serializer.c, tests/regression/1_close_TA.sh, tests/regression/1_run_TA.sh, tests/regression/runner.py
associates #140 
Add regression test of ` send_transfer()`
=> feat(api): Add send_transfer regression test

tests/regression/runner.py
Fix statistical test error, too.
successful CI result 
https://buildkite.com/dltcollab/ta-regression-test-hojmay/builds/155
Fixes #168
=> feat(reg): Add test for get_transaction_object

Makefile
=> fix(bazel): Cleanup hiredis imported from makefile

accelerator/errors.h, accelerator/http.c
* Match request URL with regular expression
* Parse parameter to use with strtok
Close #153
=> feat(server): Implement URL parser

accelerator/http.c
* Implement `set_response_content`, generate error content according to the status code returned from API function.
* Remove `ta_get_url_parameter`,  this should be moved into API callback function.
Related #154
=> feat(server): Implement generate_address API callback function

tests/regression/runner.py
Add test_find_transactions_obj_by_tag(). 
And save the API responses in dict instead of list, now. The http content and status code of API's request responses were saved in a list which has less readability. Now they were saved in a dictionary, so we can use the content and status code with key `content` and `status_code` respectively.
Fixes #169 
CI result: https://buildkite.com/dltcollab/ta-regression-test-hojmay/builds/183
=> feat(reg): Add test_find_transactions_obj_by_tag()

accelerator/server.cc
HTTP endpoint implementation of #111
=> feat(api): Add API send trytes

.bazelrc, WORKSPACE, hooks/toolchains.rc
Introduce several toolschains for x86 and arm system. Emscripten is also
viewed as a toolchain which is impotrted this time for later JS binding
usage.
Close #219
=> feat(hooks): Implement toolchains support

WORKSPACE, accelerator/apis.c, tests/iota_api_mock.cc, tests/iota_api_mock.hh
`entangled` implement MAM JS binding related APIs. Synchronize `entangled` to current commit to meet our needs.
Fixes #218
=> feat: Cleanup send/receive mam API

accelerator/common_core.c, accelerator/config.c, accelerator/config.h, accelerator/errors.h, accelerator/message.h, tests/test_cache.c, tests/test_common.cc, utils/backend_redis.c, utils/cache.h
In CLI,  turn on cache server with command `--cache Y`.
Fixes #227
=> feat(cache): Set the cache default as off

accelerator/http.c
The output message would be like : 
```
127.0.0.1  - -  [Thu Jun 27 13:26:08 2019] "GET /address" 200
```
=> feat(server): Implement req / res log message

accelerator/http.c
After this fix, branch microhttpd could pass regression tests! :tada:  
Close #208
=> fix(server): Modify error code switch case in set_response_content

.gitmodules, Makefile, third_party/BUILD
Import library `mosquitto` which is a library for MQTT client and broker
=>  feat(MQTT): Importing library mosquitto

accelerator/apis.c, accelerator/apis.h, accelerator/common_core.c, accelerator/common_core.h, accelerator/server.cc, serializer/BUILD, serializer/serializer.c, serializer/serializer.h, tests/driver.c
For downward compability, tag-related APIs are back.
=> feat(API): Add tag related fetching APIs back

accelerator/apis.c, accelerator/apis.h, accelerator/server.cc, serializer/BUILD, serializer/serializer.c, serializer/serializer.h
Fixes #267 .
Add API to dump tangle accelerator info.
=> feat(api): Add API to dump tangle accelerator info

accelerator/config.c, accelerator/config.h, accelerator/server.cc, response/ta_find_transactions_obj.c, serializer/serializer.c
Cleanup warnings mentioned in #272
=> Fix warnings in tangle-accelerator

accelerator/common_core.c, tests/driver.c, tests/test_pow.c, tests/test_serializer.c
Fixes #302.
Log error messages in `tests/driver.c`, `tests/test_pow.c`, and `tests/serializer.c`.
=> feat(tests): Enable logger in tests

README.md
Revise section Connectivity to make it more clear.
Describe buildifier in more detailed in README.
=> Fix(README): Revise section Connectivity and buildifier

accelerator/common_core.c, tests/test_common.cc, tests/test_define.h, utils/BUILD, utils/bundle_array.h, utils/pow.h
For some MAM situation, we need to save multiple bundle objects in an array.
=>  feat(utils): Add datatype bundle object array

storage/scylla_api.c, storage/scylla_api.h, tests/test_scylla.c
Different usage could use separated keyspace.
For example use different keyspcace in testing, CI and production.
=> make keyspace can be specify by parameter --keyspace

README.md, accelerator/config.c, accelerator/config.h, connectivity/mqtt/duplex_callback.c, connectivity/mqtt/pub_utils.h, connectivity/mqtt/sub_utils.c
=> cleanup: fix warnings in accelerator_mqtt

accelerator/BUILD, accelerator/apis.c, accelerator/apis.h, accelerator/http.h, accelerator/proxy_apis.c, accelerator/proxy_apis.h, accelerator/server.cc, tests/BUILD, tests/driver.c, tests/test_define.h
Fixes #292 .
Implement IRI proxy APIs, including `checkConsistency`, `getBalances`, `getInclusionStates`,  `getNodeInfo`, `getTrytes` and `removeNeighbors`.
IRI API reference: https://docs.iota.org/docs/node-software/0.1/iri/references/api-reference
=> feat(api): Implement IRI Proxy API

accelerator/BUILD, accelerator/apis.c, accelerator/common_core.c, accelerator/config.c, accelerator/config.h, accelerator/conn_mqtt.c, accelerator/errors.h, accelerator/http.c, accelerator/main.c, accelerator/proxy_apis.c, accelerator/proxy_apis.h, accelerator/server.cc, connectivity/mqtt/client_common.c, connectivity/mqtt/duplex_callback.c, connectivity/mqtt/duplex_callback.h, connectivity/mqtt/duplex_utils.c, connectivity/mqtt/pub_utils.c, connectivity/mqtt/sub_utils.c, serializer/BUILD, serializer/serializer.c, storage/scylla_api.h, tests/driver.c, tests/test_common.cc, tests/test_pow.c, tests/test_scylla.c, tests/test_serializer.c, utils/BUILD, utils/backend_redis.c, utils/logger.h, utils/pow.c
Refactor architecture of TA logger.
Reduce level number of TA logger to four and specify the logger usage.
=> Refactor architecture of TA logger

README.md, accelerator/BUILD, accelerator/apis.c, accelerator/apis.h, accelerator/http.c, accelerator/proxy_apis.c, accelerator/proxy_apis.h, accelerator/server.cc, serializer/serializer.c, serializer/serializer.h, tests/driver.c, tests/test_common.cc, tests/test_define.h, tests/test_serializer.c, utils/BUILD, utils/hash_algo_djb2.h
Implement proxy API request handlers and API url routers of both
served and microhttpd HTTP framework.
=> feat(api): Implement HTTP router of Proxy API

request/ta_send_mam.h
=> fix(mam): fix ta_send_mam typo

README.md, storage/BUILD, storage/scylla_api.c, storage/scylla_api.h, storage/scylla_table.c, storage/scylla_table.h, tests/test_scylla.c
Motivation : In the solution of reattach mechanism and permanode, we need a interface to store TXN and could be selected by status and uuid.
=> Implement automated transaction re-attachment

accelerator/config.c, accelerator/config.h, accelerator/conn_mqtt.c, accelerator/http.c, accelerator/main.c, accelerator/server.cc, connectivity/mqtt/duplex_callback.c, serializer/serializer.c, serializer/serializer.h, tests/driver.c
=> Refactor essential configuration structures

accelerator/apis.c, accelerator/apis.h, accelerator/http.c, accelerator/server.cc, serializer/serializer.c, serializer/serializer.h
Keep Tangle-accelerator connecting IRI host and port secrets is better for security
Solve : #355
=> Not reveal private TA configuration through publish APIs

accelerator/http.c
=> Show error message for URL not match only when no support API matches

accelerator/config.h
Update the TA version in `config.h`.
=> Prepare for pre-release 0.8.0

accelerator/main.c
The logger level of some of the message in `main.c` should not
be warning level.
=> fix: Change the logger level from warning to info

accelerator/BUILD, accelerator/core/BUILD, accelerator/core/response/BUILD, accelerator/core/serializer/BUILD, common/BUILD, connectivity/mqtt/BUILD, storage/BUILD, tests/BUILD
Add a new rule : build_option
If other rules need the information and macro of the build_option, just add rule `build_option` into their dependency.
close #418
=> refactor(bazel): Enhance bazel conditional build

hooks/formatter
=> feat(formatter): Add buildifier in formatter

storage/scylladb_client.h, storage/scylladb_identity.h, storage/scylladb_permanode.h, storage/scylladb_utils.h, storage/ta_storage.h
=> docs : Add Doxygen friendly file descriptions for TA storage

WORKSPACE
Fix errors in entangled found bt coverity.
This PR has passed regression test.
=> update(bazel): Synchronize entangled

accelerator/core/pow.h, connectivity/http/http.h, connectivity/mqtt/duplex_callback.h, connectivity/mqtt/duplex_utils.h, connectivity/mqtt/mqtt_common.h, connectivity/mqtt/pub_utils.h, connectivity/mqtt/sub_utils.h, utils/cache/cache.h, utils/fill_nines.h, utils/hash_algo_djb2.h, utils/timer.h
Header file descriptions was missing in several files.
Add these descriptions for doxygen
=> fix(doc): Add file description

CONTRIBUTING.md
=> doc(CONTRIBUTING): Add Contributing notice

accelerator/config.h
Bump the version number for releasing
=> refactor(config): Bump version number

accelerator/core/BUILD, accelerator/core/apis.c, accelerator/core/apis.h, accelerator/core/core.c, accelerator/core/core.h, accelerator/core/proxy_apis.c, accelerator/core/serializer/serializer.c, accelerator/core/serializer/serializer.h, common/ta_errors.h, connectivity/http/http.c, tests/driver.c, tests/test_serializer.c, utils/BUILD, utils/char_buffer_str.h
api_check_iri_connection would check the connection status
between tangle-accelerator and IRI host. Two errors will trigger
tangle-accelerator try to connect to another IRI on IRI priority list.
The first one is tangle-accelerator failed to connect to IRI host.
The other one is the connected IRI hasn't synchronized to the
latest milestone.
close #455
=> feat(api): Implement API get IRI connection

README.md
=> docs(README): Fix typo in README

tests/regression/test_suite/find_transactions_hash_by_tag.py, tests/regression/test_suite/find_transactions_object_by_tag.py
=> feat(regression): Implement regression tests for tag-related API

accelerator/config.c, accelerator/config.h
Wrong command name in config file should be
reported.
fixes #492
=> fix(config): Report wrong commands in config file

accelerator/core/apis.c, common/BUILD, common/ta_errors.c, common/ta_errors.h, connectivity/mqtt/mqtt_common.c, storage/scylladb_identity.c, storage/scylladb_identity.h, storage/scylladb_permanode.c, storage/scylladb_permanode.h
Close #468.
Add `ta_error_to_string` function that may help simplifying logger
argument.
=> feat(common): Convert enum status_t to string

accelerator/config.c, accelerator/core/BUILD, accelerator/core/apis.c, accelerator/core/apis.h, accelerator/core/core.c, accelerator/core/core.h, accelerator/core/mam_core.c, accelerator/core/request/BUILD, accelerator/core/request/request.h, accelerator/core/request/ta_recv_mam.c, accelerator/core/request/ta_recv_mam.h, accelerator/core/response/ta_send_mam.h, accelerator/core/serializer/serializer.c, accelerator/core/serializer/serializer.h, common/BUILD, common/macros.h, connectivity/http/http.c, tests/api/driver.c, tests/mam_test.c, tests/test_define.h, tests/unit-test/test_serializer.c, utils/BUILD, utils/bundle_array.h
With specifying streaming message channel protocol, user can
send streaming message with tangle-accelerator.
data_id and key are two general interface for different protocols.
relates to #291
=> feat(mam): Implement API mam receive message

accelerator/main.c, connectivity/BUILD, connectivity/common.c, connectivity/common.h, connectivity/http/BUILD, connectivity/http/http.c, connectivity/mqtt/BUILD, connectivity/mqtt/duplex_callback.c
Fixes #483.
Send back error message as what http connection does.
=> fix(MQTT): Send response when errors occured

.travis.yml, tests/coverity_analysis.sh
We apply coverity scan which is a static analysis service
on develop branch. A yml script is added for coverity scan.
Coverity scan will be invoked every Wednesday.
close #244
=> feat(test): Apply coverity scan on develop branch

reattacher/reattacher_main.c
Remove redundant quotation mark beside include header file.
=> fix(reattacher): Remove redundant quotation mark

connectivity/common.h, connectivity/http/http.c
Concatenation multiple request fragments to a complete request for large post requests.
Close #506
=> fix(http): Support large post requests

accelerator/config.h
Bump version name for next release.
close #534
=> refactor: Bump version name

accelerator/config.h
=> refacor(config): Bump version name

accelerator/config.c, accelerator/core/apis.c, accelerator/core/core.c, accelerator/core/pow.c, accelerator/core/proxy_apis.c, accelerator/core/serializer/serializer.c, common/logger.h, common/ta_errors.c, common/ta_errors.h, connectivity/common.c, connectivity/http/http.c, connectivity/mqtt/duplex_callback.c, connectivity/mqtt/duplex_utils.c, connectivity/mqtt/mqtt_common.c, connectivity/mqtt/pub_utils.c, connectivity/mqtt/sub_utils.c
Closes #502.
Applied ta_error_to_string in loggers.
=> fix: Make use of ta_error_to_string

tests/api/driver_core.c, tests/api/mam_test.c, tests/common.c, tests/common.h
Use the random trytes generator under `tests/common.h`
=> refactor(tests): Share random trytes generator

accelerator/cli_info.h, accelerator/config.h, accelerator/core/apis.c, accelerator/core/core.c, accelerator/core/core.h, accelerator/core/mam_core.c, accelerator/core/response/ta_send_mam.h, accelerator/core/serializer/serializer.h, accelerator/main.c, accelerator/mqtt_main.c, common/ta_errors.c, common/ta_errors.h, connectivity/mqtt/duplex_utils.h, docs/MQTT-mode-intro.md, docs/build.md, docs/endpoint-hal.md, storage/scylladb_client.h, storage/scylladb_identity.c, storage/scylladb_permanode.c, storage/scylladb_permanode.h, tests/api/driver_core.c, utils/cipher.h, utils/text_serializer.h, utils/timer.h
=> cleanup: Fix typos

tests/regression/common.py, tests/regression/requirements.txt, tests/regression/run-api-with-mqtt.sh, tests/regression/runner.py, tests/regression/test_suite/find_transactions_hash_by_tag.py, tests/regression/test_suite/find_transactions_object_by_tag.py, tests/regression/test_suite/generate_address.py, tests/regression/test_suite/get_tips.py, tests/regression/test_suite/get_tips_pair.py, tests/regression/test_suite/get_transactions_object.py, tests/regression/test_suite/get_transactions_object_single.py, tests/regression/test_suite/send_transfer.py, tests/regression/test_suite/send_trytes.py
Close #421.
We share the same test cases between http connection method and mqtt
ones. We could add more test suites easier later in this way.
=> feat(MQTT): Implement MQTT regression test

tests/regression/test_suite/send_transfer.py
Fixes #643.
Fix the erroneous response verification in test cases.
=> fix(regression): Erroneous response verification

endpoint/endpoint_core.c, endpoint/endpoint_core.h, endpoint/test_endpoint_core.c, tests/unit-test/test_cipher.c, utils/BUILD, utils/cipher.c, utils/cipher.h
=> fix(endpoint): Use the logger

Makefile, endpoint/endpointComp/Component.cdef, endpoint/endpoint_core.c
Generate the certification before building the endpoint Legato app.
Add the source and header files of logger.
Fix the if-else condition comparison and function argument.
=> fix(endpoint): Fix Legato app building errors

utils/connectivity/conn_http.c
Fix memory leak on http_open. The http_open will allocate the
ssl object and the net connect objects. But never free them when
the connection failed.
Close #661
=> fix(endpoint): Fix memory leak when http_open failed

endpoint/BUILD, tests/unit-test/BUILD, tests/unit-test/test_endpoint_core.c, utils/cipher.c
The endpoint_core's unit test needs to create a tangle-accelerator
before testing. After create a tangle-accelerator docker daemon on
buildkite agent for testing. It can be tested automatically.
Close #669
=> fix(endpoint): Move endpoint_core unit test into unit-test directory 

endpoint/endpointComp/endpoint.c
The arguments of the endpoint core function
send_transaction_information() can be passed with the command line.
Close #671.
=> feat(endpoint): Pass input data with command line

accelerator/core/apis.c, accelerator/core/core.c, accelerator/core/mam_core.c, connectivity/mqtt/duplex_utils.c, storage/scylladb_permanode.c
=> fix(coverity): Fix coverity reported bugs

utils/cipher.c
This commit fix the wrong error message
=> fix(endpoint): Fix null error message

accelerator/config.c, accelerator/core/serializer/ser_mam.c, common/debug.c, utils/cache/backend_redis.c, utils/cpuinfo.h
Fix errors found by CA PEM.
Read CA files until EOF, and avoid buffer overflow.
=> fix(coverity): Fix security issues coverity found 

README.md, endpoint/build-legato.sh, endpoint/unit-test/driver.sh, hooks/autohook.sh, hooks/ci_format_check, hooks/formatter, hooks/scripts/format_check, hooks/scripts/function_check, tests/coverity_analysis.sh, tests/endpoint/common.sh, tests/endpoint/test-WP77.sh, tests/regression/common.sh, tests/regression/router-sanitizer.sh, tests/regression/run-api-with-mqtt.sh, tests/regression/run-api.sh
Using 'shfmt' to format shell scripts
See: https://github.com/mvdan/sh for more information
We may need to add this into formatter
=> refactor: Format shell scripts 

hooks/formatter
Fix wrong merge conflict in hash 782a6e7.
=> fix: wrong merge conflict

Doxyfile, accelerator/config.h
Bump version name for the next release.
Close #680
=> refactor: Bump version

hooks/buildifier, hooks/ci_buildifier_check, hooks/ci_format_check, hooks/formatter, hooks/scripts/buildifier_check, hooks/scripts/format_check, hooks/scripts/function_check, tests/coverity_analysis.sh, tests/regression/router-sanitizer.sh, tests/regression/run-api-with-mqtt.sh, tests/regression/run-api.sh
Set script's shebang as portable one.
=> refactor: Enforce portable shebang 

accelerator/core/apis.c, accelerator/core/apis.h, accelerator/core/core.c, accelerator/core/mam_core.c, accelerator/core/mam_core.h, accelerator/core/request/request.h, accelerator/core/request/ta_register_mam_channel.c, accelerator/core/request/ta_register_mam_channel.h, accelerator/core/serializer/ser_mam.c, accelerator/core/serializer/ser_mam.h, common/ta_errors.h, tests/api/mam_test.c, tests/unit-test/test_cache.c, tests/unit-test/test_serializer.c
Register user identity with MAM channel seed. The return user ID is
an UUID.
Asymmetric encryption for key exchange will be implemented in the
coming PR.
=> feat(mam): Register user ID with MAM channel seed

accelerator/core/serializer/ser_mam.c, endpoint/endpointComp/endpoint.c, endpoint/endpoint_core.c, endpoint/endpoint_core.h, endpoint/unit-test/driver.sh, endpoint/unit-test/test_endpoint_core.c, endpoint/unit-test/test_http.c, tests/endpoint/test-endpoint.sh
Sending MAM message instead of embedding message in IOTA transaction
object.
Closes #616
=> feat(endpoint): Send MAM message instead txn

endpoint/BUILD, endpoint/cipher.c, endpoint/endpoint_core.c, endpoint/text_serializer.c, endpoint/text_serializer.h, endpoint/unit-test/BUILD, tests/endpoint/test-endpoint.sh, tests/unit-test/BUILD
This commit provided the logger and check for endpoint utility which
didn't have the logger and check.
Close #578
=> fix(Endpoint): Provide logger and check 

common/ta_errors.c, common/ta_errors.h, docs/endpoint-shell.md, endpoint/shell.adef, endpoint/shellComp/Component.cdef, endpoint/shellComp/shell.c, endpoint/shellComp/shell.h
This commit implement the engineering shell for mangOH Red.
To start the shell on mangOH Red. Run "app runProc shell shell",
or "app start shell". The engineering shell will listen on the
/dev/ttyHS0 on the mangOH Red and communicate with the development
host via UART.
Close #745
=> feat(Endpoint): Implement interactive shell

.ci/coverity_scan.sh, .ci/setup.sh, .github/workflows/github_actions.yml
=> CI: Migrate travis ci to github actions
