tangle_accelerator_core_api.c

Implement api_get_tips

---

BUILD
apis.h

Obey cpplint format rules or pre-commit hooks would yield errors.

Obey cpplint format rules

---

BUILD
apis.c
apis.h
serializer/serializer.c
serializer/serializer.h
serializer/test/test_serializer.c

Return transaction hashes by tags

Implement api_find_transactions_by_tag

---

BUILD
WORKSPACE
apis.c
apis.h
config.h
errors.h
server.cc

Refine boost library with served as http server handler. Following API requests with GET are also implemented:
* GET /tag
* GET /tips (only fetch all tips for now)
* GET /address

Refactor server handler

---

apis.h
serializer/test/test_serializer.c

We handle requests according to request path,
thus function `handle_request` and `command:` in send_transfer request are no longer needed.

Remove redundant function and json column

---

accelerator/BUILD
accelerator/common_core.c
cache/BUILD
cache/backend_redis.c
cache/cache.h
tests/test_common.cc

Add cache operations to ta_get_transaction_object and modify how it checks response, because get_trytes always return trytes even if transaction not found.
Part of #55

Add cache operations to ta_get_transaction_object

---

WORKSPACE
accelerator/BUILD
accelerator/common_core.c
accelerator/common_core.h
request/ta_send_transfer.h
serializer/serializer.c
tests/iota_api_mock.cc
tests/iota_api_mock.hh
tests/test_common.cc

The implementation is only for zero transaction now.
* `prepare_transfer`
* `send_trytes`
* Use `iota_client_send_trytes` for temporary

Implement ta_send_transfer

---

accelerator/common_core.c
tests/test_common.cc
tests/test_serializer.c

* `accelerator/common_core.c`: Add ret_code checking
*  `tests/test_serializer.c`: Replace constant with macro for consistency
* `tests/test_common.cc`: Compare trits with `memcmp` to remove redundant tryte_trit conversion

Code refactor

---

accelerator/apis.c
accelerator/common_core.c
accelerator/server.cc
serializer/serializer.c
serializer/serializer.h
tests/test_serializer.c

`ta_send_transfer_res_serialize` is removed because `api_send_transfer` returns the transaction object instead of transaction hash.
Close #8

Implement api_send_transfer

---

.gitignore
Doxyfile
accelerator/apis.h
accelerator/common_core.h
accelerator/config.h
accelerator/errors.h
request/request.h
request/ta_send_transfer.h
response/response.h
response/ta_find_transactions.h
response/ta_find_transactions_obj.h
response/ta_generate_address.h
response/ta_get_tips.h
response/ta_get_transaction_object.h
response/ta_send_transfer.h
serializer/serializer.h
utils/cache.h
utils/pow.h

* `/accelerator`
* `/request`
* `/response`
* `/serializer`
* `/utils`

Documentation with Doxygen

---

accelerator/server.cc

Content-type check in header should check if there is the substrings 
instead of whole strings to allow other parameters.
Fix #76

fix: content-type/media-type check

---

WORKSPACE
accelerator/apis.h
accelerator/common_core.h
request/ta_send_transfer.h
response/ta_find_transactions.h
response/ta_find_transactions_obj.h
response/ta_generate_address.h
response/ta_get_tips.h
response/ta_get_transaction_object.h
response/ta_send_transfer.h
serializer/serializer.c
serializer/serializer.h
tests/test_define.h
utils/cache.h
utils/pow.h

* Modify `types.h` include path, include_prefix is removed in CClient
* Rename helper functions in serializer, since the function names are
same as the one in CClient. Renaming resolves function redefined
error.
Close #80

Update CClient commit in WORKSPACE

---

accelerator/common_core.c
tests/BUILD
tests/driver.c

Add accelerator test driver and also option to print each execute time. Default test case would run each function one time, while with `ENABLE_STAT` it would execute 100 times and print each request time to test log. CI pipeline now upload test logs to artifact. So we can utilize these logs to output useful data or graphs afterwards.
This PR also encountered and fixed a potential memory leak which is if ta_find_transactions_obj_by_tag get more than one trasaction with given tag. Move the scope of ta_get_transaction_object_res_t can insure the memories are actually free.
Resolve #79

feat: add accelerator test driver

---

accelerator/server.cc

According to the W3C specification, the media type header should be
"Content-Type".
See-also: https://tools.ietf.org/html/rfc7231#section-3.1.1.5

fix: Correct response Content-Type header

---

accelerator/server.cc

Since API does not respond with "Access-Control-Allow-Origin" header,
the response data are blocked when calling the API from browser.
To eliminate this problem, add "Access-Control-Allow-Origin" header
to each API response.

fix: Add response header to allow CORS requests

---

accelerator/common_core.c

We do not convert hash trits at first that the transaction responsed from cache would get an incorrect hash trits.
close #90

fix: Incorrect txn hash in find_transaction_object response

---

accelerator/common_core.c

Return error code if find_transaction_object can't find any result since
default response would be null trytes instead.

fix(core): Return error if transaction not found

---

README.md
WORKSPACE
accelerator/BUILD

Add docker image support for easier installation. User can now use bazel
rules to build a docker image. The image is also uploaded to docker hub
for faster deployment with default settings.
Resolve #24

feat(docker): Add docker image rule

---

accelerator/BUILD
accelerator/common_core.c
accelerator/config.c
accelerator/config.h
tests/BUILD
tests/test_cache.c
tests/test_common.cc
tests/test_define.h
utils/BUILD
utils/backend_redis.c
utils/cache.h

Move initialize and destroy of utils interfaces to config. This PR also refactor cache interface for the need of configuration. Following modules are affected:
- cache
- pow
Part of #114

feat(config): Move utils initialize/destroy to config

---

utils/pow.c

If there were some error happened, the older version would return immediately
which would cause memory leaks. Therfore, I use `goto` instead of `return` immediately.

fix(pow): Fix memory leaks in pow.c

---

utils/pow.c

The bundle array order is actually increment from front to back. So we
should start with back to be trunk.

fix(pow): Fix bundle order of pow

---

request/BUILD
request/request.h
request/ta_send_mam_req.c
request/ta_send_mam_req.h

Use send_mam_req object to simplify the arg of api_mam_send_message().

feat(mam): Implement send_mam_req

---

accelerator/errors.h
response/BUILD
response/response.h
response/ta_send_mam_res.c
response/ta_send_mam_res.h

Use send_mam_res object to simplify the arg of api_mam_send_message().

feat(mam): Implement send_mam_res object

---

accelerator/BUILD
accelerator/apis.c
accelerator/apis.h
accelerator/server.cc
request/BUILD
request/request.h
request/ta_send_mam.c
request/ta_send_mam.h
response/BUILD
response/response.h
response/ta_send_mam.c
response/ta_send_mam.h
serializer/BUILD
serializer/serializer.c
serializer/serializer.h
tests/driver.c
tests/test_serializer.c

This PR contains following changes:
- Rename send_mam request/response type to unity with other types
- Add send_mam request/ response (de)serializer and test case
- Apply (de)serializer to send_mam API

feat(serializer): Add send_mam_message (de)serializer

---

accelerator/BUILD
accelerator/config.c
accelerator/config.h
accelerator/errors.h
accelerator/message.h
accelerator/server.cc
tests/driver.c

This PR contains following changes:
* Rename default config function to `ta_config_default_init`
* Implement `ta_config_cli_init` to get config value from CLI
* Move `iota_client_core_init` and `cache_init` to `ta_config_set`
Configuration variables should all be confirmed then start the connection to IRI or redis
* Add `ta_config_print` to print out all configurations for confirmation
Close #114 
After successfully build, and make sure you're under `tangle-accelerator/`, then execute like below:
`$  bazel-bin/accelerator/accelerator --help`
output:
```
jkrvivian:tangle-accelerator $ bazel-bin/accelerator/accelerator --help
tangle-accelerator usage:
--help                                          Show tangle-accelerator usage 
--version …
```

feat(conf): Implement CLI configuration interface

---

accelerator/errors.h
serializer/serializer.c
serializer/serializer.h
tests/driver.c
tests/test_serializer.c

Testing target transaction would disapear after snapshot (both local and global ones). 
Redisgn test driver which use the result of sending tx APIs as thr input of receiving tx APIs.
fixes #144

fix(driver): Redesign test driver for target tx disapearing

---

accelerator/apis.c
accelerator/errors.h
accelerator/server.cc

Pre-Shared Key is used for encrypt message. Remove psk so every messages can be public in MAM protocol. This PR also fix following MAM settings:
* Remove psk for public message
* Change bundle hash for receive message
* Reorder send mam init for better memory free
* Return actual status value of send mam API

fix(MAM): Remove psk for public message

---

tests/regression/runner.py

Add regression test for following API:
* mam_recv_msg
* mam_send_msg
Run program with `tests/regression/runner.py "<iri_host>:<iri_port>"`.
This test would call the local TA to run the API regression tests.
This file is formatted with `yapf`
associates #140

feat: Add MAM regression test

---

serializer/serializer.c
tests/test_serializer.c

Allow send transfer in ASCII format message and set default to ascii.
Current message format are trytes and ascii, so we check only "trytes"
to differ than default.
Resolve #145

feat(serialzer): Add message format in send transfer

---

accelerator/apis.c
accelerator/config.c
accelerator/config.h

MAM API can be serialized and saved into files. This PR create a
temporarily file to save MSS after first time. Send MAM message can be
faster in second call and after in this way.
Here's the result of test driver:
Average time of send_transfer: 2.613634
tests/driver.c:214:test_send_transfer:PASS
Average time of send_mam_message: 3.906628
tests/driver.c:218:test_send_mam_message:PASS
Resolve #149

fix(MAM): Add MAM save file

---

.gitignore
BUILD

The bazel rule `pkg_coverage` can package the folder `coverage`
into tar file, but it can't be called before run code coverage.
The code coverage result `/coverage` is hidden from git.

feat: Package code files coverage into .tar

---

accelerator/errors.h

8-bit status code is not enough for TA now, since more modules and actual error codes will be added.
The status code bitmap will be like:
* `M`: module
* `S`: severity
* `C`: actual error code
```
*---------*--------*
*|MMMMMMMM|SSCCCCCC|
*---------*--------*
```
related to #158

Expand status_t to 16-bit

---

accelerator/BUILD
accelerator/errors.h
accelerator/http.c
accelerator/http.h
accelerator/main.c

* `main.c`: server body, read config variables and start server
* `http.hc`: http utility functions
Below functions are implemented:
* ta_http_init
* ta_http_start
* ta_http_stop
* ta_http_handler: request callback function
* ta_http_header_iter: header parser callback function
* ta_http_process_request
After the build, execute: `$ bazel run //accelerator:accelerator_microhttpd`
Then you may send requests.
Close #152

feat(server): Implement server core functions with microhttpd

---

serializer/serializer.c
serializer/serializer.h

The `const` prefix should be used for constant pointer of pointer here.
However, `const char **` is constant char instead.
The strncmp must be the condition of if statement here, but the if statement
is missing here which result the raw_message will always be false.

fix(seria): Fix `const` placement and if statement

---

WORKSPACE
tests/BUILD
third_party/BUILD
third_party/BUILD.hiredis
third_party/third_party.bzl
utils/BUILD
utils/backend_redis.c

Import shared library is available in bazle, while it's still have lots
of restrictions. As of now we use git submodule and makefile to compile
dependencies. This may cause unwanted update from git submodule and
env errors. Introduce bazel rules to compile can make sure these being
take care of.
Close #184

feat(bazel): Import hiredis dependency through bazel

---

tests/regression/runner.py

Add Regression test for api find transactions by tag.
The refactoring of the test is refactored failed cases. The modified one examine the status code for each failed case. In orther words, we examine more sepcific failed situations now.
And the statistical tests have independent option in runner arguement.

feat(reg): Add regression test for api find_transactions_by_tag

---

tests/regression/runner.py

Add regression test cases for get_tips()
At this moment, get_tips() allows whatever string follows after `/tips/`.
Fixes #171 
CI result: https://buildkite.com/dltcollab/ta-regression-test-hojmay/builds/187

feat(reg): Add tests for get_tips()

---

tests/regression/runner.py

Add regression test for `api_generate_address()` and `api_get_tips_pair()`. Both APIs allow arbitrary string follows after their query string now.
CI result: https://buildkite.com/dltcollab/ta-regression-test-hojmay/builds/206
Fixes #172 #170

feat(reg) Add regression test for `api_generate_address` and `api_get_tips_pair` 

---

accelerator/apis.c
accelerator/errors.h
serializer/BUILD
serializer/serializer.c
serializer/serializer.h
utils/BUILD
utils/fill_nines.c
utils/fill_nines.h

The input tag length needs to be in 27 trytes for `ta_find_transactions_by_tag()`. Therefore `fill_nines()` needs to be called if tag's length is under 27. At the same time, `api_find_transactions_by_tag()` would return error if the length of tag is more than 27 trytes.
Fixes #195

fix(api): Patch nines for `api_find_transactions_by_tag()`

---

accelerator/apis.c
accelerator/message.h
request/ta_send_mam.c
request/ta_send_mam.h
response/ta_send_mam.c
response/ta_send_mam.h
serializer/serializer.c
serializer/serializer.h
tests/driver.c
tests/test_serializer.c
utils/fill_nines.h

Some files were not included in doxygen document. The missing files are added to doxygen produced documents in this PR. 
And in order to achieve consistency `send_mam` objects are renamed to `ta_send_mam` object.

fix: Add the missing files to doxygen document

---

WORKSPACE
accelerator/BUILD
accelerator/apis.c
accelerator/apis.h
accelerator/common_core.c
accelerator/common_core.h
accelerator/config.h
accelerator/message.h
request/BUILD
request/ta_send_mam.c
request/ta_send_mam.h
request/ta_send_transfer.h
response/BUILD
response/ta_find_transactions.h
response/ta_find_transactions_obj.h
response/ta_generate_address.h
response/ta_get_tips.h
response/ta_get_transaction_object.h
response/ta_send_mam.c
response/ta_send_mam.h
response/ta_send_transfer.h
serializer/BUILD
serializer/serializer.c
serializer/serializer.h
tests/driver.c
tests/test_serializer.c
utils/BUILD
utils/cache.h
utils/fill_nines.h
utils/pow.h

Syncgronize entangled to latest commit, and replace our implementation of `cclient_prepare_transfer()` with entangled provided exteneded API `iota_client_prepare_transfers()`.
In the latest commit, the `entangled`'s own defined variable types should be included respectively (not like what we did before).
And `mam_api_bundle_write_header_on_channel()` has removed one argument (`trint9_t msg_type_id`).
Should be merged after #203

feat: Synchronize with entangled

---

tests/regression/1_run_TA.sh

Using default port setting caused regression test failed during CI.
Now, we can assign whished port for CI as shell script argument.
CI result: https://buildkite.com/dltcollab/ta-regression-test-hojmay/builds/269

fix(reg): Reslove regression port conflicts

---

accelerator/apis.c
accelerator/common_core.c
accelerator/common_core.h
serializer/BUILD
serializer/serializer.c
serializer/serializer.h
tests/test_common.cc
tests/test_serializer.c

Discard our own implemeneted `cclient_get_tips()` and use etangled original function `iota_client_get_tips()`. The related functions in serializer.[c, h] have been removed as well.
In `api_get_tips_pair()`, we discard our own implemented `cclient_get_txn_to_approve()`, and
use entangled original function `iota_client_get_transactions_to_approve()`.

refactor(api): Use entangled original APIs iota_client_get_tips and iota_client_get_transactions_to_approve

---

accelerator/common_core.c

Use `uthash.h` provided function `CDL_FOREACH` to traverse all the elements in `ta_find_transactions_res_t`'s hash field instead of using for loop

refactor: Use utlist foreach instead for loop

---

accelerator/BUILD
accelerator/apis.c
accelerator/config.c
accelerator/config.h
map/BUILD
map/mode.c
map/mode.h
request/ta_send_mam.c
request/ta_send_mam.h
serializer/serializer.c
tests/BUILD
tests/test_map_mode.c
tests/test_serializer.c

Move basic mam api into wrapper called map/mode. The wrapper is also moved
under the map directory which is stand for Mask Authenticated Privacy. It
will be a seperate binary to implement mam utility in the future.
Add a new argument "order" to specific channel order.  Functions are now
from map target and add test case for it. Type of send mam request is alos
refactored.

 feat(accel): Refactor send mam API

---

accelerator/apis.c
map/mode.c
map/mode.h
request/BUILD
request/ta_send_mam.c
request/ta_send_mam.h
serializer/serializer.c
tests/test_map_mode.c
tests/test_serializer.c

- Make send mam API able to check length of message and create exact sufficient mam channel depth. 
- Add optional parameter prng to make client able to create unique channel id.

feat(api): Enhance send mam API with length detection

---

accelerator/apis.c
accelerator/common_core.c
tests/regression/1_close_TA.sh
tests/regression/1_run_TA.sh
tests/regression/1_run_TA_API.sh
tests/regression/runner.py

After TA was synchronized to the closer entagled commit, some of TA's response
fields were renamed, because we used entangled original serialzers.
To meet the different naming in the response of TA, the testing response's json key
have to be changed to cooperate with TA's response json key.
And the last cleanup causes empty response error of `ta_find_transactions_obj_by_tag`.
We fix that here.
Furthermore, the CI failures were resulted from bazel didn't have enough time
to build TA which makes no TA to process request sent from runner.py.
The problem can be solve easily by giving more time for bazel to build TA.
But in some situations, if the agent is parallelly executing other task (other CIs), then it may take more time for bazel to build TA or even causes failure.
CI result: …

fix: Fix regression and common core errors

---

WORKSPACE

fix(WORKSPACE): Bump bazel rules docker to 0.7.0

---

accelerator/common_core.c

To avoid failure caused by a turning off cachnig server, we need add one more if statement to protect it.

fix: Detect cache server turning off situation

---

accelerator/http.c

If the GET request has the same url with the POST apis, it should return
a method_not_allowed response. Thus we should check if body is empty or not
in the callback functions before execution.

fix(server): Check request body in POST api callback functions

---

accelerator/BUILD
accelerator/errors.h
accelerator/http.c
accelerator/http.h
accelerator/main.c

feat(server): Implement microhttpd framework

---

serializer/serializer.c
tests/test_serializer.c

Refactor response format of APIs, [format link](https://hackmd.io/SGVFkhpCQUi53wJIgWiY8Q)
I do not refactor the format of `tips/` and `/tips/pair`, since they use cclient directly.
Close #247

feat(api): Refactor response JSON format

---

WORKSPACE

The stable version of `cclient` was released. 
See https://github.com/iotaledger/entangled/releases/tag/cclient-v1.0.0-beta

feat: Synchronize to stable entangled version

---

accelerator/apis.c
serializer/serializer.c
serializer/serializer.h

The response of send_transfer() was in the wrong format.
And this PR fix unicode problem of send_transfer() as well.

fix(api): Fix send_tranfer() response format

---

accelerator/apis.c
accelerator/common_core.h
response/ta_find_transactions.c
response/ta_find_transactions.h
serializer/serializer.c
serializer/serializer.h
tests/test_serializer.c

Reorder serializing functions into `serialize(*source, *dest)`.
This ordering would makes these functions more clear and
at the same time, it is following the same ordering entangled using.

refactor(serialize): Reorder serialize functions arguements

---

README.md

Since we have a new image repository on the Docker Hub, update the
readme document to use image comes from that repository.
See also: https://hub.docker.com/r/dltcollab/tangle-accelerator

docs: Update docker image name

---

README.md
accelerator/BUILD

To make the update the docker image workflow simple, add the rule to
publish the docker image to Docker Hub.

feat: Add rule to push docker image to Docker Hub

---

accelerator/BUILD

Because of the inconsistent Bazel rule coding style, CI check always
failed.

fix: Fix Bazel rule coding style

---

.bazelrc

Because the container_push rule from rules_docker is written in
Python and its depend on the Python 2 packages, we need to enforce the
Bazel to use Python 2 with this rule.
These settings can be removed after the rules_docker migrate this rule
with go.
See also:
- https://github.com/bazelbuild/rules_docker#known-issues
- https://github.com/bazelbuild/rules_docker/issues/842

fix: Enforce Bazel to use Python 2

---

accelerator/main.c
accelerator/mqtt_interface.c
accelerator/server.cc

With `logger_helper_init()` provided in newer version of
entangled(tag ="cclient-v1.0.0-beta"), codes that initialize logger
can be shortened.

refactor(api): Update the way to initialize logger

---

accelerator/apis.c
accelerator/apis.h
accelerator/errors.h
accelerator/main.c
accelerator/server.cc

Race condition happens when doing `cJSON_parse`, both cclient library and deserialization in TA would use the function, thus those are wrapped with mutex lock.

feat(api): Add lock to avoid race condition

---

accelerator/apis.c
accelerator/common_core.c
accelerator/common_core.h

`mam_api_add_trusted_channel_pk` should take chid in `tryte_t`
instead of `flex_trit_t`.
Moreover, for simplicity of `apis.c`, `the tryte_t` to
`flex_trit_t` conversion is moved to `common_core.c`

fix(MAM): Wrong datatype for MAM function

---

tests/driver.c

The MAM relates function is still under developing,
so we temporarily comment these functions.

fix(api): Disable MAM tests

---

accelerator/BUILD
accelerator/config.c
accelerator/config.h
accelerator/errors.h
accelerator/main.c
accelerator/message.h
accelerator/server.cc

Fixes #268 
With this commit, tangle accelerator can read the configuration file using `--config` CLI. When `--config` and other CLI (e.g., `--ta_host`、`--ta_port`) are passed in command-line arguments together,  `--config` has lower precedence.

feat(api): Read setting from configuration file

---

accelerator/apis.c
accelerator/server.cc

Fixes #299 .
Allow invalid transaction tag that is less than 27 trytes, and fill nines to expand it to 27 trytes afterwards.

feat(api): Handle invalid transaction tag

---

accelerator/apis.c
accelerator/common_core.c
accelerator/config.c
accelerator/conn_mqtt.c
accelerator/errors.h
accelerator/http.c
accelerator/main.c
accelerator/server.cc
connectivity/mqtt/client_common.c
connectivity/mqtt/duplex_callback.c
connectivity/mqtt/duplex_utils.c
connectivity/mqtt/pub_utils.c
connectivity/mqtt/sub_utils.c
serializer/serializer.c
utils/backend_redis.c
utils/pow.c

The previous logger function (e.g., `log_error()`) we used to log message
was too troublesome. With this commit, it will be more convenient to
log message by `ta_log_xxx()`. (e.g., `ta_log_error()`)

refactor(logger): Wrap log_xxx() into macro

---

accelerator/apis.c
accelerator/common_core.c
tests/regression/runner.py

The tests in regression test are still using the deprecated API
format. We should correct it to accommodate the current using
API format.
In order to avoid some possible crashes, we block unicode messages.
Now, both tag and message are not allowed to be unicode string.
CI result: https://buildkite.com/dltcollab/ta-regression-test-hojmay/builds/474

feat(reg): Fix regression test API format

---

accelerator/errors.h
storage/BUILD
storage/scylla_api.c
storage/scylla_api.h
tests/BUILD
tests/test_define.h
tests/test_scylla.c

Why: for Permanode to store transactions with scyllaDB
How: add storage folder with Bazel BUILD
@storage/scylla_api.c - insert_transaction_into_bundleTable => insert transaction
- select_transactions_with_bundle => show all transaction in specific bundle

Interface for accessing transactions with ScyllaDB backend

---

accelerator/common_core.h

`cclient_get_txn_to_approve` is an deprecated function, and its
declaration should be removed as well.

cleanup(core): Remove deprecated function

---

Makefile

The default make all would be better not build MQTT related third party library.

improve(make): Separate MQTT from make all

---

README.md

Makefile has removed MQTT from default building.
We have to use MQTT label to build the third party
library of MQTT.

fix(readme): Synchronize build command

---

accelerator/errors.h

Currently we can not use logger as following.
`ta_log_error(" description : %s\n", error_code);`
This commit is goal to fix it.
we can also simply use logger as `ta_log_error("error_code\n")`
instead of `ta_log_error("%s\n", "error_code\n")`

Make the logger support formatting without placeholders 

---

connectivity/mqtt/BUILD
connectivity/mqtt/duplex_callback.c
hooks/pre-commit/03-function-check
hooks/scripts/function_check
serializer/BUILD
serializer/serializer.c
tests/driver.c
tests/test_serializer.c

As mentioned in #301, I searched the project directory for the existence of `gets`, `strcpy` and `sprintf`  strings, and changed them to suggested fixes.
I think rules should also be added to detect the usage of dangerous functions in compile time like [git/banned.h](https://github.com/git/git/blob/master/banned.h), but I have no idea where to add this header file at this point.

Apply security rules

---

accelerator/server.cc

The API fetching the information of TA returned status code 0.
This commit fix this problem.
fix #333

fix(server): Fix API TA info status code

---

accelerator/apis.c

Motivation : The error cases of ta_get_info_serialize are not only due to OOM. Inherit return value from ta_get_info_serialize would be more accurate.

Correct the return value of function api_get_ta_info

---

accelerator/http.c
accelerator/http.h
accelerator/main.c

The infinite loop in `accelerator/main.c` costs high CPU usage while launching, this could be replaced with `getchar()`.

fix(server): Apply pause() to wait signal for termination in MHD

---

accelerator/BUILD
accelerator/apis.c
accelerator/common_core.c
accelerator/common_core.h
accelerator/errors.h
accelerator/server.cc
tests/BUILD
tests/test_timer.c
utils/BUILD
utils/timer.c
utils/timer.h

The server hangs when user requests `/address` and IRI connections are
down.
At this moment, we can't shutdown the server by sending `SIGINT` or
`SIGTERM` since served has already registered the signal handler for
those signals.
I added a timeout to `api_generate_address`, separating a new `/address`
request to a new thread, and simply cancel the thread if exceeded the
time limit.

Fix server hang on request to /address

---

tests/driver.c

Close #304.
From bazel user manual, we can add `--test_arg=<a string>` to the
`bazel test` command to pass additional arguments.
For example, we could run `bazel test -c dbg //tests:driver
--test_arg=--iri_host="localhost"` to set the IRI host.

Allow IRI_HOST and IRI_PORT set via command line for test case

---

accelerator/BUILD
accelerator/config.c
accelerator/config.h
accelerator/conn_mqtt.c
accelerator/main.c
accelerator/message.h
accelerator/server.cc
storage/BUILD
storage/scylla_api.c
storage/scylla_api.h
tests/driver.c
tests/test_scylla.c

**Motivation**: To insert new pending transaction and query transactions' status, TA needs connecting to a ScyllaDB host. 
**Usage**: Connect to ScyllaDB host when performing initialization. The default setting of connection is disabled.
- Use  "--db_host [host]" to specify the host.
This PR would close #346.

Add an option for ScyllaDB connection

---

storage/scylla_api.c
storage/scylla_api.h
storage/scylla_table.c
storage/scylla_table.h
tests/test_scylla.c

Implement select functions either by status, id or hash.
Add timestamp column to identity table and implement time elapsed function
The time elapsed could be used for transaction reattachment.  Preform reattachment when a transaction has pended for a while.
Close #360

Rework data model and query functions for transaction reattachment 

---

storage/scylladb_client.c
storage/scylladb_client.h
storage/scylladb_identity.c
storage/scylladb_identity.h
tests/test_scylladb.c

User should call db_insert_tx_into_identity to insert new transactions. Give transaction hash and status and get a new generated version 4 UUID string.
Close #361

Use version 4 UUID as the identifier of transactions

---

accelerator/server.cc

One can get Ta information by following request now.
`GET /info`
At least one path segment is necessary for GET method.
And the registration should happen before registering path {*}
close #377

Amend the API to get TA information

---

accelerator/BUILD
accelerator/config.c
accelerator/config.h
accelerator/conn_mqtt.c
connectivity/mqtt/BUILD
connectivity/mqtt/mqtt_common.c
connectivity/mqtt/mqtt_common.h
connectivity/mqtt/pub_utils.h
connectivity/mqtt/sub_utils.h
serializer/BUILD
serializer/serializer.c
serializer/serializer.h
tests/test_serializer.c

Fixes #352.
This commit merges `accelerator` and `accelerator_mqtt` into `accelerator`. To use the mqtt version, we need to add the option `--define build=mqtt` after the original command.

Separate connection policy with build options

---

README.md
accelerator/common_core.c
accelerator/config.c
accelerator/config.h
accelerator/http.c
accelerator/message.h
accelerator/proxy_apis.c
accelerator/proxy_apis.h
accelerator/server.cc
tests/driver.c
tests/test_timer.c

We provide two way to process proxy API.
1. Pass request body to IRI directly.
2. Deserialize the request, then pass it to IRI.
This PR use the 1st solution which supports all the
IRI core API.
A user can choose which way they want with CLI argument
`--proxy_passthrough`

feat: Proxy API passthrough support

---

accelerator/http.c

Remove the RGE_NOSUB flag to get the position of matches.
Close #371

Check the URL length does match the specific regular expression

---

accelerator/BUILD
connectivity/mqtt/BUILD

Error was caused without including `config.c`
and `config.h` in bazel rule `accelerator`.
The error caused varriable `iota_service.serializer_type` was written
wrongly.
fix #381

fix: bazel caused  IRI connection error

---

accelerator/BUILD
accelerator/config.c
accelerator/config.h
accelerator/conn_mqtt.c

We wrongly defined `MQTT_ENABLE` in rule `accelerator` which causes the whole program crashed.
`MQTT_ENABLE` should be a building identifier for MQTT is chosen only and keep consistency of define building identifier.

fix: Fix wrongly define MQTT_ENABLE in accelerator

---

accelerator/http.c

Fixes #389.
`ta_http_url_matcher` needs to match the whole input url exactly, so it
would be better to allow a trailing slash in the regular expression.

Allow trailing slash in url matcher

---

tests/BUILD

The definition of ta_core_t in translation unit driver.c is different from config.c and main.c after merging #395.
Since the code in driver.c does declare ta_core_t, the MQTT_ENABLE should be defined when using option --define mqtt=enable at build time.
We could find that the size of ta_core_t will be different if #ifdef MQTT_ENABLE have different results
```
show the sizeof(ta_core_t)
sizeof ta_core_t in driver.c = 744
sizeof ta_core_t in config.c = 768
```
close #399

Consolidate MQTT specific translation units

---

README.md
accelerator/BUILD
accelerator/config.c
accelerator/config.h
accelerator/conn_mqtt.c
accelerator/main.c
accelerator/server.cc
storage/BUILD
tests/BUILD
tests/driver.c
tests/empty_test.c
tests/test_common.cc
tests/test_scylladb.c

To enable ScyllaDB backend and tests :
Add Bazel CLI option --define db_enable
Otherwise, TA won't build ScyllaDB backend and tests by default.
close #383

Conditional build for ScyllaDB backend and its dependance

---

accelerator/http.c
tests/regression/0_build.sh
tests/regression/1_run_TA_API.sh
tests/regression/runner.py

Fixes #359, #393.
Removed `test_find_transactions` since this route no longer exists now.
More checks are added in case of non-200 status code which may lead
the test to stop unexpectedly.

Fix regression test

---

accelerator/http.c
accelerator/server.cc

Fix memory leak on functions that call ta_get_url_parameter(), which will malloc a buffer, but never free the memory.
Fix memory leak on functions that create CJSON objects without delete.
Close #405

Fix memory leak on functions to processing HTTP requests

---

accelerator/http.c
tests/test_common.cc

Without giving terminate character `\0`, the HTTP payload
may contain some miscellaneous string.
fixes #408

fix: Fix miscellaneous request payload

---

README.md
accelerator/BUILD
accelerator/apis.c
accelerator/apis.h
accelerator/config.c
accelerator/http.c
accelerator/server.cc
connectivity/mqtt/duplex_callback.c
response/BUILD
response/ta_send_transfer.h
serializer/BUILD
serializer/serializer.c
serializer/serializer.h
storage/scylladb_client.c
storage/scylladb_client.h
storage/scylladb_identity.c
tests/driver.c
tests/test_scylladb.c

Insert a new pending transaction after successfully send a transfer message.
3 new APIs
- /identity/hash/<hash> : get identity info by hash
- /identity/id/<id> : get identity info by uuid string
- /transaction/id/<id> : get transaction info by uuid string
Close #362

Implement transaction reattachment related APIs

---

accelerator/config.c

If we give a CLI argument without key which would be two
dash (`--`) only, TA would open fail.
Therefore, we simply remove the dashes without assigning
keys.
fixed #390

fix: Fix error as CLI argument without giving key

---

Makefile

The top level Makefile clean rule directed to a wrong directory.

fix(build): Fix wrong Makefile clean rule

---

connectivity/http/http.c

If we send GET request under root URL path, the HTTP
router would not handle it and return segmentation fault. We
need to use function `process_method_not_allowed_request()`
to block this error

fix(http): Fix NULL request error under root path

---

WORKSPACE

Syncronize hooked entangled commit to the latest one.
And the remote repo is changed to our forked entangled
repo
In addition, bazel rule of served is removed, since it has been
removed from the code base.

refactor(bazel): Sync entangled hooking commit

---

accelerator/core/core.c
accelerator/core/pow.c

`attach_res->trytes` is a pointer which points to a memory space. Each elements in the `attach_res->trytes` is a `flex_trit_t`, so we need to multiple the length of the hash_array to the size of `flex_trit_t` but not the size of `hash8019_array_p`.
In the 2nd commit, `tx_trits` is a defined array, so it would never be `NULL`.

Fix incorrect assigned size and remove dead code

---

accelerator/core/request/ta_find_transaction_objects.c

If `ta_find_transaction_objects_req_t` object was not
corretly declared (i.e. OOM), the destructor
`ta_find_transaction_objects_req_free()` would be called.
However, in this situation, we would derefere the NULL
pointer req.

fix(req): Fix NULL pointer dereference

---

docs/reattacher.md
reattacher/BUILD
reattacher/reattacher_main.c
storage/scylladb_identity.c
storage/scylladb_identity.h
tests/test_scylladb.c

** (updated in #430) We need to update the target to Entangled version to fix the function `iota_client_replay_bundle`
Get all pending transactions from ScyllaDB every 5 mins. Change the status of transaction if it has been confirmed.  Preform reattachment if it has been pended since 30 minutes ago.
Close #414

feat(db): Implement transaction reattach service

---

accelerator/cli_info.h
accelerator/config.c

the 4th argument of `getopt_long()` is an array
of `struct option`. And this array should be ended with
a `struct option` filled with zeros.
See man page or [this link](https://linux.die.net/man/3/getopt_long) for more information
fixes #436

fix(cli): Append zeros in CLI option array

---

connectivity/http/http.c
tests/test_core.cc

Fix errors when building TA with `bazel build //accelerator`

cleanup(http): Fix warnings in bazel rule accelerator

---

accelerator/config.c
reattacher/reattacher_main.c
tests/test_scylladb.c

There are some options that are exclusive to certain tests. When we add all required options in our CI pipeline at once, some options would miss after read an unknown option.

fix : continue to get cli options after an unknown option

---

README.md

When using Makefile to build third party libraries, some tools are necessary.
In this commit, those required tools are added into README

docs(README): Add requirements for makefile

---

accelerator/main.c
accelerator/mqtt_main.c
connectivity/http/http.c

Without initializing logger in different source files, the logger name
would display `main` only.
fixes #460

fix(logger): Fix wrong logger name

---

accelerator/cli_info.h
accelerator/config.c
accelerator/mqtt_main.c
docs/build.md

MQTT host and MQTT subscribe topic root can be assigned with CLI command `--mqtt_host` and `--mqtt_topic_root` respectively
close #294

feat(config): Add CLI for MQTT configures

---

storage/scylladb_identity.c
storage/scylladb_identity.h
storage/scylladb_permanode.c
storage/scylladb_permanode.h
storage/scylladb_utils.c
storage/scylladb_utils.h
tests/test_scylladb.c

- Truncate(clear all data) instead of dropping table. 
- Remove tests for permanode. Those functions do not be used currently.
To test the insertion and selection, we need an empty table. The previous method is dropping old tables when performing tests. But dropping tables will change the schema. After schema changement, we need to wait for the ScyllaDB cluster to make an agreement, but we execute the tests concurrently. It is hard to wait enough time among each test. Actually, the schema should not be changed if we do not change the data model.
close #458

fix(db) : Revise tests for ScyllaDB backend

---

README.md
accelerator/cli_info.h
accelerator/config.c
accelerator/core/serializer/serializer.c
accelerator/main.c
accelerator/mqtt_main.c
common/logger.h

When verbose mode is off, logger would be release after message,
`Tangle-accelerator starts running` has be printed out.
TA was set in quiet mode in default. Now it has been changed to
verbose mode. TA would turn on verbose mode (logging message
would be printed in default). To turn on quiet mode, a user can use
CLI commanf `--quiet`
close #464

Turn off logger after initialization and set verbose mode by default

---

tests/regression/common.sh
tests/regression/run-api.sh

Fixes #464.
Changed the option name from `verbose` to `quiet`.
I've also changed the order to parse `cli_arg` and `build_arg`,
which was placed incorrectly and regarded as empty argument before.

fix(regression): Fix command line option

---

accelerator/cli_info.h
accelerator/config.c
accelerator/config.h
accelerator/core/apis.c
accelerator/core/apis.h
accelerator/core/core.c
accelerator/core/core.h
connectivity/http/http.c
tests/driver.c

This is an emergent PR.
If milestone doesn't work, any transaction which processing GTTA
can't be able to be sent successfully. For a temporary workaround,
we add a new CLI commmand to turn GTTA off.

Hotfix: Allow sending transfer when milestone shutdown

---

connectivity/http/http.c

We need to allow header field `X-IOTA-API-Version` in `Access-Control-Allow-Headers` to  preflight response.

fix(http): Revise X-IOTA-API-Version CORS issue

---

accelerator/cli_info.h
accelerator/config.c
accelerator/main.c
accelerator/mqtt_main.c

Commands `cache`, `proxy_passthrough` and `quiet` are no
argument commands. We need to do corresponding operations.

fix(cli): Fix no argument commands

---

README.md

The link of docs/build.mb was wrong.

docs(README): Fix unavailable link

---

accelerator/BUILD
docs/build.md

Use the docker command to release the docker image to Docker Hub, and we
could modify the metadata of docker image, e.g. REPOSITORY, TAG.
Since we already enforce the bazel to use Python 2 in .bazelrc, we don't
need to mention syntax error problem in document.

refactor: refine docker image release workflow

---

accelerator/cli_info.h
accelerator/config.c
accelerator/config.h
accelerator/core/core.c
accelerator/core/core.h
accelerator/core/serializer/serializer.c
accelerator/core/serializer/serializer.h
accelerator/main.c
connectivity/http/http.c
tests/unit-test/test_serializer.c

Use an extra thread to check the IRI connection status.
If someting is going wrong, then change to another host on
priority list.
The priority of the listed IRI hosts depends on the oder of CLI args.
`tangle-accelerator --iri_address <ADDR1> --iri_address <ADDR2> --iri_address <ADDR3>`
On the example presented above, the priority is `ADDR1` > `ADDR2` > `ADDR3`.
close #452

feat(main): Check IRI connection periodically

---

connectivity/http/http.c

The following content-type are accepeted in tangle-accelerator
* application/json
* application/json;
* application/json; charset=UTF-8
* application/json; charset=utf-8
* application/json;charset=utf-8
And both uppper case and lower case of Content-Type and content-type
are accpeted from this PR.
fixes #503

fix(http): Accept content type encoding UTF-8

---

accelerator/core/core.c

Fixes #500.
`ta_timer_stop` returns SC_OK on success, the condition in if statement
should be `ta_timer_stop(..) != SC_OK` instead of `!ta_timer_stop(..)`

Fix error logging message in timer

---

tests/api/driver.c

We have removed using random trytes to send transfer, so the
random number generation is not necessary here.

test(driver): Remove redundant random seed generation

---

WORKSPACE
accelerator/BUILD

Because docker image could not use the host system's runtime package,
it is necessary to include the runtime package to docker image.
We are upgrade the rules_docker to v0.9.0, and use the "package_managers"
to include runtime package to docker image.

chore: add uuid-runtime package to docker image

---

tests/api/driver_setting.py

Be aware that the parameter naming is changed from testnet to devnet
since PyOTA v3.0.0.

fix(CI): Allow python script to select testnet or mainnet

---

WORKSPACE
hooks/formatter

`hooks/formatter` didn't format root WORKSPACE.

fix(hooks): Format WORKSPACE with formatter

---

tests/test_define.h
tests/unit-test/test_cache.c
utils/cache/backend_redis.c
utils/cache/cache.h

We need a list in cache server to store all the UUIDs
of buffered transactions. When tangle-accelerator reconnect to
IRI, tangle-accelerator would iterate all the elements in the
list, and use the stored UUIDs to fetch the stored transaction
body in cache server.
relates to #522

feat(cache): Implement LIST operations for cache

---

accelerator/cli_info.h
accelerator/config.c
accelerator/config.h
accelerator/core/apis.c
accelerator/core/apis.h
accelerator/core/core.c
accelerator/core/core.h
connectivity/http/http.c
tests/api/driver.c

If milestone doesn't work, any transaction which processing GTTA
can't be able to be sent successfully. For a temporary workaround,
we add a new CLI commmand to turn GTTA off.
close #536

feat(config): Add CLI command to disable GTTA

---

.travis.yml

- **Use Ubuntu 18.04 for newer version of UUID library**
In the default environment of Travis CI, it uses Ubuntu 16.04.
The corresponding UUID library is version 2.27.1, which lacks of the
macro UUID_STR_LEN.
Hence we need to use Ubuntu 18.04 and the corresponding UUID library
version 2.31.1 to make the building process work.
- **Install Cassandra C client library on Travis CI**
Install reference:
https://docs.datastax.com/en/developer/cpp-driver/2.15/topics/installation/#ubuntu

Fix Travis CI and Coverity Scan

---

accelerator/main.c

The callback function of `pthread_create()` was in wrong
varaible type.

fix(main): Fix unmatching argument type of pthread

---

accelerator/cli_info.h
accelerator/core/serializer/serializer.h
common/macros.h
common/ta_errors.c
common/ta_errors.h
connectivity/common.c
connectivity/mqtt/BUILD
connectivity/mqtt/duplex_callback.c
connectivity/mqtt/duplex_utils.c
connectivity/mqtt/mqtt_common.h
connectivity/mqtt/usage.md

Fixes #529.
The route to `api_send_trytes` is `tryte`.
The route to `api_find_transaction_object` is separated to `transaction` and `transaction/object` to support single and multiple transaction hashes.

feat(MQTT): Add missing routes

---

accelerator/config.c
accelerator/config.h
accelerator/core/BUILD
accelerator/core/apis.c
accelerator/core/apis.h
accelerator/core/core.c
accelerator/core/core.h
accelerator/core/response/ta_send_transfer.c
accelerator/core/response/ta_send_transfer.h
accelerator/core/serializer/serializer.c
accelerator/main.c
common/macros.h
tests/api/BUILD
tests/api/common.c
tests/api/common.h
tests/api/driver.c
tests/api/driver_core.c
tests/api/mam_test.c
utils/cache/backend_redis.c
utils/cache/cache.h

Once a transction request is failed, since the connection of IRI
or the problems on Tangle, then tangle-accelerator would push
transction object to buffer. We used redis as buffer DB.
Each failed request would have a corresponding UUID. Client can
use this UUID to view the current status of the failed request.
Run function `broadcast_buffered_txn()` in thread `health_track()`
in `main.c` which would broadcast buffered transactions to Tangle.
CI would needs corresponding modifications.

feat(core): Broadcast buffered transaction objects

---

tests/api/common.c

To integrate driver_core into CI, and using concise CI scripts,
we should allow function `driver_core_cli_init()` to take a NULL
argument. Once a NULL argument of `driver_test_cases_t` is provided,
even though testing command `T` and `H` are assigned, no tags and
hashes will be set.
The updated CI command will be as following:
```
- name: "bazel test asan"
artifact_paths:
- "bazel-testlogs/tests/api/driver/*.log"
- "bazel-testlogs/tests/unit-test/*/*.log"
command:
- "make"
- "python3 tests/api/driver_setting.py <URL> devnet 'bazel test --config=asan //tests/api/...' '--test_arg --iri_host=<HOST> --test_arg --iri_port=<PORT> --test_arg --cache'"
- "bazel test -c dbg --config asan //tests/unit-test/..."
```

fix(test): Allow driver_core_cli_init take NULL args

---

accelerator/cli_info.h
accelerator/config.c

This PR implement the CLI for `buffer_list_name` and `done_list_name`
Assigning different name for different tests in CI can avoid data racing during CI.

feat(config): Set buffer list name with CLI

---

accelerator/core/serializer/serializer.c
common/ta_errors.c
common/ta_errors.h
connectivity/common.c
connectivity/common.h

We currently assume all the size of requests of `api_send_transfer`
in smaller than one transaction. To notify client who sent oversize
message in `send_transfer`, now, tangle-accelerator will report
the error mesage that the size of message is oversize.
The error response would be `{"message": "In body 'message', requested message is too long."}`

fix(http): Report when requested msg too long

---

connectivity/common.c

Fix the build error after #563

fix(common): correct undeclared macro for HTTP message

---

accelerator/config.c
accelerator/config.h
accelerator/core/core.c
accelerator/main.c

Remove CLI option `iri_address` that will overwrite options `iri_host` and `iri_port`.
Make options  `iri_host` and  `iri_port` support multiple addresses separated by comma.
For example `./accelerator --iri_host  host1,host2, ...`
Correct the misused TA binding port and address.
Correct error casting and range checking of CLI options.
Close #583 #584

fix(core): integrate conflicting IOTA conf and fix incorrect TA conf

---

accelerator/core/BUILD
accelerator/core/core.h
common/BUILD
common/debug.c
common/debug.h

There are some debugging tool functions are implemented in
`entangled`, but we need to migrate to `iota.c` first, then
we could use those debugging tools easily.
So I mirgated some debugging tools, and implemented one extra
debugging function `transaction_cmp` which can compare all the
fields of two transaction objects.
close #565

feat(common): Implement debugging tool

---

accelerator/config.c
accelerator/core/apis.c
accelerator/core/core.c
accelerator/core/mam_core.c
accelerator/core/mam_core.h
accelerator/core/request/ta_recv_mam.c
accelerator/core/request/ta_recv_mam.h
accelerator/core/response/ta_send_mam.c
accelerator/core/response/ta_send_mam.h
accelerator/core/serializer/serializer.c
common/ta_errors.h
tests/api/BUILD
tests/api/driver.c
tests/api/mam_test.c
tests/unit-test/test_serializer.c

We planned to send mam message on mam endpoint private keys.
However, sending with channel private keys are much easier to
implement, so `api_send_mam_message()` has been refactored.
It would send message with channel private keys.
Once there is only one private left, then this API will automatically
send the announcemnet for the next channel. Related tests have been
implemented as well.
Fix #513

refactor(mam): Send mam message on channel keys 

---

accelerator/core/response/ta_fetch_txn_with_uuid.c
accelerator/core/response/ta_find_transactions.c
accelerator/core/response/ta_find_transactions_obj.c
accelerator/core/response/ta_send_transfer.c

Some initializers of the datatype of tangle-accelerator don't have
the protection if-condition for Out Of Memory situation.
if-condition of `(*res)->hashes` and `utarray_clear()` for
`(*res)->txn_obj` are both redundant, so we could remove them.
Fix #596

refactor: Cleanup improper/redundant operations

---

utils/cache/backend_redis.c

We don't need to print the information that cache option has been
turned off everytime we are using it.

refactor(cache): Set cache logger in debug mode

---

README.md
accelerator/BUILD
accelerator/cli_info.h
accelerator/config.c
accelerator/config.h
accelerator/core/apis.c
accelerator/core/apis.h
accelerator/core/proxy_apis.c
accelerator/core/serializer/serializer.c
accelerator/main.c
connectivity/http/http.c
connectivity/mqtt/duplex_callback.c
tests/api/driver.c
utils/BUILD
utils/cpuinfo.h

Run MHD by using internal thread (or thread pool) doing  `epoll()`
Set the size of thread pool by cli option
--ta_thread <value>
Create new `iota_client_serivce_t` for each HTTP request to avoid race condition and lock contention.
Correct cli option ta_thread to required argument
close #569
To preserve a least one physical processor, set the limit of threads number to logical processor number - 1(2) (According to whether CPUs support HyperThreading or not)
close #592

feat(core): Handle IOTA-aware HTTP request with threadpool and epoll

---

accelerator/core/apis.c
accelerator/core/mam_core.c
accelerator/core/response/response.h
accelerator/core/response/ta_recv_mam.c
accelerator/core/response/ta_recv_mam.h
accelerator/core/serializer/serializer.c
accelerator/core/serializer/serializer.h
tests/api/mam_test.c
tests/unit-test/test_serializer.c

If the chid1 (the next channel ID) existed, then return it in the
API response.
The tests of `test_send_read_mam_bundle()` has been covered by
other tests.
Close #593

refactor(mam): Return chid1 with recv_mam_message 

---

endpoint/BUILD
endpoint/endpoint.c
endpoint/hal/BUILD
endpoint/hal/device.c
endpoint/hal/device.h
endpoint/test_endpoint.c
tests/unit-test/test_cipher.c
tests/unit-test/test_text_serializer.c
tests/unit-test/test_tryte_byte_conv.c
utils/cipher.c
utils/cipher.h
utils/connectivity/BUILD
utils/connectivity/conn_http.c
utils/https.c
utils/https.h
utils/text_serializer.c
utils/text_serializer.h

Eliminate compilation warnings when building utils, test and endpoint.
The warning was generated from -Wextra's sign-compare flag.
Close #603

cleanup(endpoint): Eliminate compilation warnings

---

accelerator/core/apis.c
accelerator/core/apis.h
accelerator/core/mam_core.c
accelerator/core/mam_core.h
accelerator/core/request/ta_send_mam.c
accelerator/core/request/ta_send_mam.h
accelerator/core/response/ta_send_mam.c
accelerator/core/response/ta_send_mam.h
accelerator/core/serializer/serializer.c
common/macros.h
tests/api/mam_test.c
tests/unit-test/test_serializer.c

To follow the pattern of other APIs, the MAM-related operations
are moved to `mam_core`, and some of datatypes are renamed.

refactor(mam): refactor MAM APIs

---

accelerator/config.h
accelerator/main.c
tests/unit-test/BUILD
tests/unit-test/test_scylladb.c

Include necessary headers.
Correct the function signature for the pthread start routine.
Remove unused parameters.

cleanup: Eliminate compilation warnings

---

accelerator/core/core.c
accelerator/core/mam_core.c
accelerator/core/serializer/serializer.c
accelerator/main.c
accelerator/mqtt_main.c
connectivity/mqtt/duplex_callback.c
connectivity/mqtt/mqtt_common.c
storage/scylladb_identity.c
storage/scylladb_identity.h
utils/bundle_array.h

`bundle_array_copy()` has been implemented now, so
`utarray_push_back()` can copy the whole `bundle` object to the last
element of the bundle_array object. Therefore, we can use
`bundle_transaction_free()` instead of using `free()` on
`bundle_transaction_t` object.
Memory leaks and the statement that execution can't reach are
solved, too.

fix(coverity): Fix errors reported by Coverity

---

connectivity/http/http.c

With URL path `mam/send`, a user can send MAM message
With URL path `mam/recv`, a user can receive MAM message.
API `recv_mam_message()` has been changed to POST method from this
PR, so the old GET method matcher has been removed here.

fix(router): Sync url path to MAM implementation

---

endpoint/endpoint.c
tests/unit-test/test_cipher.c
tests/unit-test/test_text_serializer.c
utils/BUILD
utils/cipher.c
utils/cipher.h
utils/text_serializer.c
utils/text_serializer.h

The HMAC is a specific type of message authentication code(MAC)
involving a cryptographic hash function and a secret cryptographic key.
Same as other MAC, HMAC is used to verify both the data integrity and
the authenticity of a message. We used sha256 as default hash function
to calculate the HMAC.
Two new structure members `hmac` and `timestamp` are added into cipher_ctx.
The timestamp used the source from Unix Epoch. The timestamp is one of
the source to calculate the HMAC.
Close #608

feat(endpoint): Add HMAC support for AES encryption

---

accelerator/core/core.c
accelerator/core/response/ta_send_transfer.c
accelerator/core/response/ta_send_transfer.h
accelerator/core/serializer/serializer.c
tests/unit-test/test_serializer.c

Tangle-accelerator would return the uuid and the address of
failed transaction request.
The example response is as following:
```
{"uuid":"b76ad723-660a-44d7-bea5-26cc87ccbd05",
"address":"POWEREDBYTANGLEACCELERATOR99999999999999999999999999999999 \
99999999999999999999999"}
```
close #619

feat(api): Return address with UUID in failed requests

---

accelerator/core/pow.c
tests/api/driver.c
tests/regression/test_suite/send_transfer.py

Sending invalid tag with `iri-host` flag enabled will cause
SEGV. The ta_pow_flex didn't handle the NULL pointer when
ta_pow_dcurl returned NULL.
Close #625

fix(core): Fix invalid memory operation when sending transfer with invalid tag

---

accelerator/core/mam_core.c
accelerator/core/mam_core.h
accelerator/core/request/ta_send_mam.c
accelerator/core/request/ta_send_mam.h
accelerator/core/serializer/serializer.c
common/ta_errors.h
tests/api/mam_test.c
tests/unit-test/test_serializer.c
utils/bundle_array.h

The current implemetaion of MAM service is a data structure which is
similar to linked-list. This structure causes searching time increase
linearly, so if the user is searching some information with a large
N, then then elapsing time would be really long, too.
Therefore, in this PR, tangle-accelerator starts to support searching
MAM message from a given channel ID which can dramatically reduce
searching time with a proper given channel ID.
Close #610

feat(mam): Send mam message from given chid 

---

common/macros.h
endpoint/endpoint.c
tests/unit-test/test_text_serializer.c
utils/BUILD
utils/text_serializer.c
utils/text_serializer.h

There are individual parameters of serialize_msg and
deserialize_msg. The individual parameters are the same as
ta_cipher_ctx's member. We can pass a ta_cipher_ctx pointer
instead of individual parameters.
Close #627

fix(endpoint): Use ta_cipher_ctx pointer

---

README.md
docs/build.md

Closes #611.
Add `build_type=debug` and `build_type=profile` documentation in section
`Building Options`.

doc: Add documentation for different build types

---

.gitmodules
Makefile
WORKSPACE
third_party/BUILD
third_party/mbedtls.BUILD
utils/BUILD
utils/connectivity/BUILD

It's hard to build endpoint library with mixed build system.
This commit removed the http-parser and the mbedtls submodules
from GNU Make build system and changed them to build from Bazel.
The http_parser changed to use the source from entangled. Add
`@http_parser` into deps if needed.
The mbedtls's version from entangled has not been updated for a long
time. So the mbedtls source is still pull from github. But changed the
build system from GNU Make to Bazel. In order to avoid conflict with
the same library inside entangled. The mbedtls library which pulled
from github add a suffix `2_16_6`. Add `@mbedtls_2_16_6` into deps
if needed.
Close #647

fix(endpoint): Revise endpoint build targets in favor of Bazel

---

endpoint/BUILD

The previous host is for deployment. This commit reset the
endpoint default host to localhost for consistency. The localhost
is the default setting inside tangle-accelerator.
Close #606

endpoint(fix): Reset default host

---

.gitignore
Makefile
endpoint/BUILD
endpoint/endpoint.adef
endpoint/endpointComp/Component.cdef
endpoint/endpointComp/endpoint.c
endpoint/endpointComp/endpoint.h
endpoint/endpoint_core.c
endpoint/endpoint_core.h
endpoint/test_endpoint_core.c
utils/cipher.c

The files and directory structure are changed.
The directory endpoint/endpointComp is for building the Legato app.
The endpoint/endpoint.c is renamed as endpoint/endpoint_core.c to
separate the core functions. Same as the endpoint/endpoint.h.
New:
To build the endpoint Legato app, use the command 'make legato'.
It is implemented with the mkapp command.
Besides, the shared library libendpoint.so can be generated with Bazel
as well.
Close #576.

feat(endpoint): Legato AF integration

---

endpoint/endpoint_core.c

The endpoint_core.c didn't unify the format by clang-format. Reformat it.
Close #664

cleanup(endpoint): Unify the format

---

endpoint/endpointComp/Component.cdef

Fix the undefined symbol problem when executing the Legato endpoint app.

fix(endpoint): Fix the undefined symbol

---

Makefile
WORKSPACE
accelerator/BUILD
accelerator/config.c
accelerator/config.h
accelerator/core/BUILD
accelerator/core/core.c
accelerator/core/mam_core.c
accelerator/core/request/BUILD
accelerator/core/response/BUILD
common/BUILD
connectivity/http/BUILD
connectivity/mqtt/BUILD
endpoint/BUILD
endpoint/endpointComp/Component.cdef
endpoint/hal/BUILD
endpoint/test_endpoint_core.c
reattacher/BUILD
storage/BUILD
utils/BUILD
utils/cache/BUILD
utils/connectivity/BUILD
utils/text_serializer.c

To support some critical fixes in lastest IOTA C language library,
we should migrate the dependent library from 'entangled' to 'iota.c'
close #650

refactor(WORKSPACE): Migrate IOTA library to iota.c

---

Makefile
docs/endpoint.md
tests/unit-test/BUILD
tests/unit-test/test_http.c
utils/BUILD
utils/connectivity/conn_http.c
utils/connectivity/conn_http.h
utils/https.c

The message which sent to tangle-accelerator has been encrypted. So
the HTTP connection would not be unsafe. Support the HTTP connection
would let us setting unit-test for endpoint more easily. The HTTPS
connection still supports. To enable the HTTPS connection, add --define
https=enable when building endpoint. See docs/endpoint.md for more
information.
Close #655

feat(endpoint): Support plain HTTP connection

---

utils/https.c
utils/https.h

The HTTP(S) module didn't check the return status from conn_http
operations. This commit adds checks inside HTTP(S) module.
Close #667

fix(endpoint): Add check inside HTTP(S) module

---

accelerator/config.h
accelerator/core/apis.c
accelerator/core/core.c

Querying 'find_transasction_obj_by_tag' with a tag which has huge amount of
relating transactions would cause cclient failed to deserialize the
response.
Now, tangle-accelerator would respond 100 transaction objects in
maximum.
Closes #656
Fixes #652

fix(core): Limit the maximun response fetch by tag 

---

.gitignore
Makefile
docs/endpoint.md
endpoint/BUILD
endpoint/endpointComp/endpoint.c
endpoint/platform/simulator/build.mk
endpoint/platform/wp77xx/build.mk
hooks/formatter

This commit adds the build instructions for generating endpoint test
or app with different target. For compatibility with legato framework,
we use the GNU Make build system to build endpoint. Use "make legato"
to generate endpoint app.
The macro TARGET intends to the target to generate. The default TARGET
is the platform on your development host. Set the TARGET like
TARGET=wp77xx to generate specific platform endpoint app.
The macro ENABLE_ENDPOINT_TEST is for generating the endpoint app in test mode.
Set ENABLE_ENDPOINT_TEST=true to enable generating test mode endpoint app.
The endpoint uses the sierra framework as based runtime system.
Developers need to set up the sierra development environment
to build endpoint as specific target. See docs/endpoint.md for
more information.
The default …

feat(endpoint): Improve endpoint build instructions

---

Makefile
endpoint/BUILD
endpoint/endpointComp/endpoint.c
endpoint/endpoint_core.c
endpoint/endpoint_core.h
endpoint/unit-test/test_endpoint_core.c

- Set configuration when executing endpoint application instead of building it.
The command line option '--host', '--port' and '--ssl-seed" are added.
- Remove the unused macros.
- Change send_transaction_information for passing the host, port and SSL seed.

feat(endpoint): Specify host-port pair and SSL seed at runtime

---

Makefile
common/ta_errors.c
common/ta_errors.h
docs/endpoint.md
endpoint/endpoint.adef
endpoint/endpointComp/Component.cdef
endpoint/endpointComp/endpoint.c
endpoint/endpoint_core.c
endpoint/endpoint_core.h
endpoint/hal/device.h
endpoint/platform/simulator/build.mk
endpoint/platform/wp77xx/BUILD
endpoint/platform/wp77xx/build.mk
endpoint/platform/wp77xx/impl.c

This commit Implements the wp77xx platform for endpoint.
The AirPrime WP7702 LPWA module is the first verified device.
See https://www.sierrawireless.com/products-and-solutions/embedded-solutions/products/wp7702/
for more information.
The resolv.conf is removed. Change to use the system's default /etc/resolv.conf.
Close #679

feat(endpoint): Implement wp77xx platform

---

endpoint/unit-test/driver.sh

This commit provided unit-test script for endpoint to use on buildkite.
The test script will test all the unit-test inside endpoint/unit-test
via bazel. The bazel test will test all the unit-test in three configs,
"asan" ,"tsan" and "ubsan".
Close #689

test(endpoint): Provide unit-test script for endpoint 

---

Makefile
docs/endpoint-hal.md
docs/endpoint-platforms.md
endpoint/endpoint.adef
endpoint/endpointComp/Component.cdef
endpoint/endpoint_core.c
endpoint/endpoint_core.h
endpoint/hal/device.c
endpoint/platform/BUILD
endpoint/platform/simulator/BUILD
endpoint/platform/simulator/impl.c

This commit implements the simulator platform for endpoint.
The simulator is an instance of endpoint HAL, dedicated to control-flow
and protocol verification. The simulator will be used for testing the
endpoint functionality and verified the endpoint behavior.
The process of adding a new platform has been simplified. Only need
to provide "impl.c" and "build.mk" inside new platform. See
endpoint-hal.md for more information.
The section "hal/Makefile" inside endpoint-hal.md has been removed. The
hal/Makefile will not be used anymore.
Close #640

feat(endpoint): Implement the simulator platform 

---

.gitignore
docs/endpoint.md
endpoint/build-legato.sh
endpoint/platform/simulator/build.mk
tests/endpoint/common.sh
tests/endpoint/test-WP77.sh
tests/endpoint/test-endpoint.sh

This commit provided two script for endpoint automated test on
buildkite.
The "test-endpoint.sh" will test the endpoint app
on development platform.
The "test-WP77.sh" will generate the endpoint app and
pack the binary which can be uploaded on to WP77XX target.
The build command for development platform has been changed.
Use "make legato" to generate native app.
Close #691

test(endpoint): Provide automated test script

---

Makefile
docs/endpoint.md
endpoint/endpointComp/Component.cdef
endpoint/endpointComp/endpoint.c
tests/endpoint/test-WP77.sh

This commit changed the macro TARGET to EP_TARGET. To avoid the conflict
macro which also defined in Legato AF.
Close #696

fix(endpoint): Rename conflict macro

---

accelerator/main.c
endpoint/platform/simulator/impl.c
endpoint/unit-test/driver.sh
tests/regression/common.sh
tests/regression/router-sanitizer.sh
tests/regression/run-api.sh

Building tangle-accelerator with sanitizer, and run regression test
with the just built tangle-accelerator. With this procedure, we can
test router with sanitizers.
Now once tangle-accelerator has been initialized, tangle-accelerator
will send SIGUSR1 to the parent bash script. The bash script will wait
for the signal, then run the Python script.

feat(test): Add sanitizer for router

---

endpoint/build-legato.sh

This commit will reduce the build process of endpoint. The
Legato AF will be downloaded when the "legato" directory is not exists.
Close #700

fix(endpoint): Reduce the build process of legato target

---

endpoint/endpointComp/endpoint.c
endpoint/hal/device.c

The endpoint will always get specific device during compile-time.
This commit fixed the error message which generated from ta_device.

Fix(endpoint): Fix device not found error message

---

hooks/format-exclude-list
hooks/formatter

The autoformat hook doesn't need to format the legato project.
Close #713

fix(Endpoint): Ignore to format legato project

---

accelerator/config.c
accelerator/config.h
accelerator/main.c
endpoint/unit-test/driver.sh
tests/regression/common.sh
tests/regression/router-sanitizer.sh
tests/regression/run-api-with-mqtt.sh
tests/regression/run-api.sh

Passing signal `SIGUSR1` to parent process to notify parent process
that tangle-accelerator has been successfully initialized would cauase
tangle-accelerator terminate immediatrly.
To fix this, UNIX domain socket is used to notify regression test
script that tangle-accelerator has been successfully initialized.

fix(test): Notify initialization by domain socket 

---

endpoint/endpoint_core.c

The DNS resolver had already been provided by mbedtls inside
mbedtls_net_connect.
Close #720

fix(Endpoint): Remove DNS resolver inside endpoint

---

endpoint/diagnose.adef
endpoint/diagnoseComp/Component.cdef
endpoint/diagnoseComp/diagnose.c
endpoint/diagnoseComp/diagnose.h

Record the signal strength, GPS data and time in log.
TODO: Get the correct time with the consideration of time zone.
Related to #688.

feat(endpoint): Implement diagnose app

---

endpoint/connectivity/conn_http.c
endpoint/connectivity/conn_http.h
endpoint/endpoint_core.c
endpoint/https.c
endpoint/https.h
endpoint/unit-test/BUILD
endpoint/unit-test/test_http.c
tests/endpoint/test-endpoint.sh

The MAM protocol need to handle the HTTP(S) response from
HTTP(S) request. This commit provided the HTTP(S) response from
the http_parser. The buffer of string inside the https_response_t
and the response instance should always be free after the request.
Close #704

feat(endpoint): Provide HTTP(S) response for endpoint

---

tests/regression/common.sh
tests/regression/run-api-with-mqtt.sh
tests/regression/run-api.sh
tests/regression/test_suite/send_trytes.py

Fixes #717.
Since "tips/pair" API is removed, we can no longer depend on
the original API.
However, the original modification to send_trytes test suite
depends on the proxy_passthrough feature. Therefore, I removed
proxy_passthrough from build options and enable it everytime we
run the regression test.

fix(regression): Fix failed send_trytes test suite

---

accelerator/core/mam_core.c

Define `mam_encrypt_key_t` object in the middle of the function would
cause SEGV when the `mam_encrypt_key_t` object being freed.
And using `ta_error_to_string` to generate the string which is going to
be printed in logger.
For #706

fix(mam): Move definition to avoid SEGV fault 

---

endpoint/connectivity/conn_http.c

The double free error would occurred when HTTP connection failed.
This commit fix the double free error inside http_open.
Close #723

fix(Endpoint): Fix double free error

---

tests/endpoint/common.sh
tests/endpoint/test-WP77.sh
tests/endpoint/test-endpoint.sh

Change the host and port input from the terminal will let endpoint
to test on buildkite more friendly.
Close #729

fix(Endpoint): Specify host info from CLI

---

accelerator/core/serializer/ser_mam.c

Some request fields in tangle-accelerator expect the JSON value is
string. Tangle-accelerator may fail if the request that should be
string is not given in string
Fixes #733

fix(serializer): Ensure not derefering not-string field

---

tests/regression/router-sanitizer.sh
tests/regression/run-api.sh

Regression tests failed to connect to tangle-accelerator.
The URL in testing scripts are using environment variable
instead of hard-coded URL now.
Fixes #746

fix(tests): Fix regression tests connection failure

---

endpoint/endpointComp/endpoint.c

The app can be exited by the exit function call. The exit status
can also be caught by the buildkite more easily than the log.

fix(Endpoint): End the process via exit function

---

docs/endpoint.md
endpoint/endpoint.adef
endpoint/endpointComp/Component.cdef
endpoint/platform/wp77xx/build.mk
tests/endpoint/common.sh

This commits add the data API and the library required by the socket connection.
The sandboxed option should be set to "true" after the DNS problem fixed
by the new firmware release.
The leaf shell should be started manually since the interface search
path for legato was added.
Close #710

fix(Endpoint): Add data connection for socket connection

---

connectivity/http/http.c

The existence of spaces would cause tangle-accelerator is not able to
recognize the header field `Content-Type`.

fix: Allow spaces in Content-Type

---

accelerator/core/apis.c
accelerator/core/core.c
accelerator/core/core.h
accelerator/core/mam_core.c

'iota_client_find_transaction_objects' would fail when finding too many
transaction objects at one time. Now, tangle-accelerator would find
transaction object one by one.

fix(core): Find txn object with one txn each time

---

accelerator/BUILD
accelerator/cli_info.h
accelerator/config.c
accelerator/config.h
accelerator/core/BUILD
accelerator/core/apis.c
accelerator/core/apis.h
accelerator/core/core.c
accelerator/core/core.h
accelerator/core/periodical_task.c
accelerator/core/periodical_task.h
accelerator/core/serializer/ser_mam.c
accelerator/core/serializer/ser_mam.h
accelerator/main.c
connectivity/http/http.c
tests/api/BUILD
tests/api/mam_test.c
tests/api/test_periodical_task.c
tests/unit-test/test_cache.c
tests/unit-test/test_serializer.c
utils/cache/backend_redis.c
utils/cache/cache.h

Tangle-accelerator would respond an UUID for every `send_mam_message()`
request. This UUID can be used as querying data for
`api_fetch_buffered_request_status()`.
`api_fetch_buffered_request_status()` serves as the API to search
the current status of both buffered MAM request and buffered
transaction objects.
Closes #624

feat(mam): Return UUID as the repsonse of send MAM message 

---

accelerator/config.c
utils/cache/backend_redis.c

Tangle-accelerator reports failed to initialize caching service, when
caching service successfully started.

fix(cache): Report when cache failed to initialize

---

accelerator/cli_info.h
accelerator/config.c
accelerator/config.h
accelerator/main.c
tests/regression/common.sh
tests/regression/router-sanitizer.sh
tests/regression/run-api-with-db.sh
tests/regression/run-api-with-mqtt.sh
tests/regression/run-api.sh
tests/regression/ta_waiting.sh

Regression tests were hanging since sometimes the file of UNIX domain socket may exist. The existence of UNIX domain socket may be caused by tangle-accelerator didn't  be successfully terminated. Sometimes regression tests were cancelled or failed, in these cases tangle-accelerator may not be terminated, and the port has been used by this hanging tangle-accelerator. We may use docker to solve this issue

fix(tests): Fix the issues regression test hangs

---

accelerator/BUILD

For some operating issues, the repository on Docker Hub has been moved
from `dltcollab` to `biilabs`.

refactor: Migrate Docker Hub repo to biilabs

---

endpoint/endpoint_core.h

The doxygen comment is not consistent with the function header.
This commit update the doxygen description to consistent with the
function header.

fix(Endpoint): Update doxygen description

---

.gitignore
.gitmodules
common/ta_errors.c
common/ta_errors.h
docs/endpoint.md
endpoint/Makefile
endpoint/OBDComp/BUILD
endpoint/OBDComp/can-bus/BUILD
endpoint/OBDComp/can-bus/can-utils.c
endpoint/OBDComp/can-bus/can-utils.h
endpoint/OBDComp/monitor/BUILD
endpoint/OBDComp/monitor/Component.cdef
endpoint/OBDComp/monitor/monitor.c
endpoint/OBDComp/obd_pid.h
endpoint/OBDMonitor.adef
hooks/ci_buildifier_check

This commit implements the OBDII component which receives OBDII
packet from the CAN BUS socket. The packet will be serialized by
flatbuffer and be compressed by brotli.
The can-bus directory implements the CAN BUS utility for CAN BUS
communication.
There are various standard interfaces for OBD. For TA-endpoint,
we use OBD-II standard interfaces.
For a specific purpose, we only implements service 01 and service 09
with some of pids. Those service and pids can be seen to
OBDComp/obd_pid.h.
Close #752

feat(Endpoint): Implement OBDII component

---

docs/OBD2-emulator.md
endpoint/OBDComp/emulator/BUILD
endpoint/OBDComp/emulator/obd_emulator.c
endpoint/OBDComp/emulator/obd_emulator.h
endpoint/OBDComp/emulator/script.sh

This commit implements the OBDII emulator for specific purpose.
The OBDII emulator only supports seldom OBDII service and pids.
The supports service and pids can be seen to OBDComp/obd_pid.h.

feat(Endpoint): Implement OBDII emulator

---

common/logger.h
common/ta_errors.c
common/ta_errors.h
crypto/BUILD
crypto/ecdh.c
crypto/ecdh.h
tests/unit-test/BUILD
tests/unit-test/test_crypto.c

We will combine ECDH and ECDSA for station to station protocol which can be used for key exchange.
In this PR, only ECDH has been implemented.
For #560

feat(mam): Implement ECDH for MAM key exchange

---

endpoint/Makefile
endpoint/shell.adef
endpoint/shellComp/Component.cdef
endpoint/shellComp/shell.c

This commit adds the set-private-key command into endpoint shell to
let the user to set the private key(device key) into secure storage.
Close #781.

feat(Endpoint): Add new command into endpoint shell

---

endpoint/Makefile

The github actions will failed on endpoint make clean. But this is
not error. This commit add a fix to ignore error when make clean
failed.

fix(Endpoint): Ignore make clean failed error

---

common/ta_errors.c
common/ta_errors.h
endpoint/OBDComp/endpointService/Component.cdef
endpoint/OBDComp/monitor/Component.cdef
endpoint/OBDComp/monitor/monitor.c
endpoint/OBDMonitor.adef
endpoint/endpoint.adef
endpoint/endpointComp/endpoint.c
endpoint/platform/impl.h
endpoint/platform/legato-target/impl.c
endpoint/platform/simulator/impl.c

This commit changes the hardcoded private key inside the legato targets
and the simulator.
For legato targets, the private key will be fetched from secure storage.
The key should be set by the legato shell before the endpoint executes.
If the key doesn't exist in the secure storage, the error would be show.
For the simulator, the private key and the device ID will be generated
into the endpoint.conf if the private key and the device ID doesn't
found.
The secure storage adapter also removed inside this commit, since the
simulator would store the private key and device into the "endpoint.conf"
for simulating the secure storage.
Close #779

fix(Endpoint): Update private key source
